### ISSUE TITLE
SLPDB Hanging

### ISSUE THREAD

**Issue by christroutner** [simpleledger/SLPDB#42] opened 2019-08-29 16:00 UTC
This Issue was initially reported in the SLPDB Operators Telegram channel.

I've been seeing a 'hanging' behavior in SLPDB where it simply stops processing. It doesn't error, and it doesn't exit. I managed to reproduce this state on two separate machines overnight:

- A dedicated machine running SLPDB in the docker container (the Mint box running Linux Mint).
- In a Virtual Machine running on my dev box. 

I had both syncing all night, both running off commit https://github.com/simpleledger/SLPDB/commit/fe3f8df762e2fb66e62f9b72c1e2915d25eb1ef1

## Dev box output
```
...
[INFO] JSON RPC: getRawTransaction 3728841607b5559c2691ab24914f6c7be2ca3ddd207af5460070e1362384d8ca
SLPJS Result: false (3728841607b5559c2691ab24914f6c7be2ca3ddd207af5460070e1362384d8ca)
SLPJS Invalid Reason: Token outputs are greater than possible token inputs.
[INFO] Updating confirmed TNATxn SLP data for 279350c56bac24e422c0a1d625f1abd29ccafee3e10787443469105577fc7565
[INFO] JSON RPC: getRawTransaction 279350c56bac24e422c0a1d625f1abd29ccafee3e10787443469105577fc7565
[INFO] Updating confirmed TNATxn SLP data for 16a40eca8bf6a1d4b913820718db2361686a9371e4b4ad82998c0566cf7a3052
[INFO] JSON RPC: getRawTransaction 16a40eca8bf6a1d4b913820718db2361686a9371e4b4ad82998c0566cf7a3052
SLPJS Validating: 16a40eca8bf6a1d4b913820718db2361686a9371e4b4ad82998c0566cf7a3052
SLPJS Result: false (16a40eca8bf6a1d4b913820718db2361686a9371e4b4ad82998c0566cf7a3052)
SLPJS Invalid Reason: Token outputs are greater than possible token inputs.
```

## Mint box output
```
...
[INFO] JSON RPC: getRawTransaction eda7665cc377faaad4a29182726a3ce6b7e06c6bdf735224eff7dff58b869290
SLPJS Validating: eda7665cc377faaad4a29182726a3ce6b7e06c6bdf735224eff7dff58b869290
SLPJS Result: true (eda7665cc377faaad4a29182726a3ce6b7e06c6bdf735224eff7dff58b869290)
SLPJS Result: true (83f62d17516c05e684ea742a12c41941b6d4dda8fe6cf54038ab3e7d263148f2)
SLPJS Result: true (0860168b6ce410800e5d0a12d96534bbdd0aad7f7e416523bb0304524740f4ad)
[INFO] Updating confirmed TNATxn SLP data for 1a07d6d3fb321fbb6c80b5b6ba26d86ec8bc1733edb05b5ffccd2e7b9fb9a3f9
[INFO] JSON RPC: getRawTransaction 1a07d6d3fb321fbb6c80b5b6ba26d86ec8bc1733edb05b5ffccd2e7b9fb9a3f9
[INFO] Updating confirmed TNATxn SLP data for 83f62d17516c05e684ea742a12c41941b6d4dda8fe6cf54038ab3e7d263148f2
[INFO] JSON RPC: getRawTransaction 83f62d17516c05e684ea742a12c41941b6d4dda8fe6cf54038ab3e7d263148f2
SLPJS Validating: 83f62d17516c05e684ea742a12c41941b6d4dda8fe6cf54038ab3e7d263148f2
SLPJS Result: true (83f62d17516c05e684ea742a12c41941b6d4dda8fe6cf54038ab3e7d263148f2)
```

It just looks like normal output, but there is no more console output. I sent some token transactions and these instances of SLPDB do not register it. They aren't registering any SLP token traffic or doing any further processing. They are just hanging. No errors. It didn't exit.

The RAM isn't very high. The processor is basically idle.

Both systems are running:
- node.js v10+ 
- Typescript v3.5.3
- MongoDB 4+

The only similarity in the outputs that I'm seeing between the two hanging machines is that they both appear to have finished the same processing loop at the same point before hanging. 

The `SLPJS Result:` is the last line for both. I'm assuming the `SLPJS Invalid Reason:` is unique to particular token that was being processed at the time on the dev box (probably bread token).

**Comment by christroutner** [comment] 2019-08-29 16:03
Note: Both machines were *not* syncing from genesis. They had previous data in their databases. I was pulling the latest commits to master yesterday to debug another issue, and left them to finish syncing over night.

**Comment by christroutner** [comment] 2019-08-29 17:55
I ran again on the local Dev box with commit 53ce78e3066eda2f00012e9583a684e2f75540a4 and experienced the hanging again. Here is the output before it hung:

```
...
SLPJS Validating: 38376879ee4b7c08984baa4de88ed6979309eef8c8cd3627677f2d57fc644dda
[INFO] JSON RPC: getRawTransaction 38376879ee4b7c08984baa4de88ed6979309eef8c8cd3627677f2d57fc644dda
[INFO] JSON RPC: getRawTransaction 199e987b6d7bdd307972a759970df3d2d6be6b1303a60f0ffb7aa6885877ffe4
[INFO] JSON RPC: getRawTransaction c1ebbb73c00acdc3fca20c8622c6e8e6b2fe458c18f00730eeef1705387bc27c
SLPJS Validating: 199e987b6d7bdd307972a759970df3d2d6be6b1303a60f0ffb7aa6885877ffe4
[INFO] JSON RPC: getRawTransaction 2601e0395c40d76b708fdf29b07cf8f31c6c0cefa1d9c00bc684a44365519861
SLPJS Validating: e736a4628ef7a00b46f496ebbe4b1fda5a5caa0fb293972eb779b8aced6c2947
SLPJS Result: true (e736a4628ef7a00b46f496ebbe4b1fda5a5caa0fb293972eb779b8aced6c2947)
SLPJS Result: true (199e987b6d7bdd307972a759970df3d2d6be6b1303a60f0ffb7aa6885877ffe4)
SLPJS Result: true (38376879ee4b7c08984baa4de88ed6979309eef8c8cd3627677f2d57fc644dda)
[INFO] Updating confirmed TNATxn SLP data for 199e987b6d7bdd307972a759970df3d2d6be6b1303a60f0ffb7aa6885877ffe4
[INFO] JSON RPC: getRawTransaction 199e987b6d7bdd307972a759970df3d2d6be6b1303a60f0ffb7aa6885877ffe4
SLPJS Validating: 199e987b6d7bdd307972a759970df3d2d6be6b1303a60f0ffb7aa6885877ffe4
SLPJS Result: true (199e987b6d7bdd307972a759970df3d2d6be6b1303a60f0ffb7aa6885877ffe4)

```

**Comment by jcramer** [comment] 2019-08-29 17:58
do you start the app using:

`npm start` or `tsc && node --max_old_space_size=8192 index?`

**Comment by christroutner** [comment] 2019-08-30 14:36
I start with `npm start`.

I've observed this 'hang up' phenominon multiple times on both my local dev box and in a Docker container running on a separate device. I'll add the data I collected last night below this, but here is the pattern I've found:

- The problem is happening after the local validator is run in `localvalidator.ts/isValidSlpTxid()`.
- The problem is happening when SLPDB updating a confirmed transaction.

## Additional instances of the hang up
```
Docker container:
[INFO] Updating confirmed TNATxn SLP data for 172a58b472cf19c12c7efae4e8f8a08b627e9b65b5b9a29354101285d077ebae
[INFO] JSON RPC: getRawTransaction 172a58b472cf19c12c7efae4e8f8a08b627e9b65b5b9a29354101285d077ebae
SLPJS Validating: 172a58b472cf19c12c7efae4e8f8a08b627e9b65b5b9a29354101285d077ebae
SLPJS Result: true (172a58b472cf19c12c7efae4e8f8a08b627e9b65b5b9a29354101285d077ebae)

Dev box:
[INFO] Updating confirmed TNATxn SLP data for 08b63797a9716c9d9836a34ad8facf57f673c54279b7c5338ce04cb83e43c728
[INFO] JSON RPC: getRawTransaction 08b63797a9716c9d9836a34ad8facf57f673c54279b7c5338ce04cb83e43c728
SLPJS Validating: 08b63797a9716c9d9836a34ad8facf57f673c54279b7c5338ce04cb83e43c728
SLPJS Result: true (08b63797a9716c9d9836a34ad8facf57f673c54279b7c5338ce04cb83e43c728)
[INFO] Updating confirmed TNATxn SLP data for 080c4462d353d14be605e9522fa0a6feb4cf1be2c67b01b6394406ee7a6f40ae
[INFO] JSON RPC: getRawTransaction 080c4462d353d14be605e9522fa0a6feb4cf1be2c67b01b6394406ee7a6f40ae
SLPJS Validating: 080c4462d353d14be605e9522fa0a6feb4cf1be2c67b01b6394406ee7a6f40ae
SLPJS Result: true (080c4462d353d14be605e9522fa0a6feb4cf1be2c67b01b6394406ee7a6f40ae)
[INFO] Updating confirmed TNATxn SLP data for 0749bcc4dbf0690e69139e7fb8b5ad0a8652eba2717110bf572f116409c82562
[INFO] JSON RPC: getRawTransaction 0749bcc4dbf0690e69139e7fb8b5ad0a8652eba2717110bf572f116409c82562
SLPJS Validating: 0749bcc4dbf0690e69139e7fb8b5ad0a8652eba2717110bf572f116409c82562
SLPJS Result: true (0749bcc4dbf0690e69139e7fb8b5ad0a8652eba2717110bf572f116409c82562)


Dev box:
[INFO] JSON RPC: getRawTransaction 08ca21d1c8564508f6f41ba1c1feb5079216509f741d68d4bb539689e76cf939
SLPJS Validating: 08ca21d1c8564508f6f41ba1c1feb5079216509f741d68d4bb539689e76cf939
SLPJS Result: true (08ca21d1c8564508f6f41ba1c1feb5079216509f741d68d4bb539689e76cf939)
[INFO] Updating confirmed TNATxn SLP data for 054740694da335b8f80e76dd04dda89a3854b0562f89d9f45e5e0e1b429d79a5
[INFO] JSON RPC: getRawTransaction 054740694da335b8f80e76dd04dda89a3854b0562f89d9f45e5e0e1b429d79a5
SLPJS Validating: 054740694da335b8f80e76dd04dda89a3854b0562f89d9f45e5e0e1b429d79a5
SLPJS Result: true (054740694da335b8f80e76dd04dda89a3854b0562f89d9f45e5e0e1b429d79a5)
[INFO] Updating confirmed TNATxn SLP data for 0524ad004c0064e0254e784ef0cbf9f560d63732d691a3a887715fe0dc215593
[INFO] JSON RPC: getRawTransaction 0524ad004c0064e0254e784ef0cbf9f560d63732d691a3a887715fe0dc215593
SLPJS Validating: 0524ad004c0064e0254e784ef0cbf9f560d63732d691a3a887715fe0dc215593
SLPJS Result: true (0524ad004c0064e0254e784ef0cbf9f560d63732d691a3a887715fe0dc215593)

Docker container:
SLPJS Result: true (162009f215423839c00e0aebd3f08aea48ef02fef783e020ea92970ee880e360)
[INFO] Updating confirmed TNATxn SLP data for 0ff1874550bc31f9b6065f8f8d7dca2884b731bf329899c6b1b89920a01127da
[INFO] JSON RPC: getRawTransaction 0ff1874550bc31f9b6065f8f8d7dca2884b731bf329899c6b1b89920a01127da
SLPJS Validating: 0ff1874550bc31f9b6065f8f8d7dca2884b731bf329899c6b1b89920a01127da
SLPJS Result: true (0ff1874550bc31f9b6065f8f8d7dca2884b731bf329899c6b1b89920a01127da)
[INFO] Updating confirmed TNATxn SLP data for 03aa89d2dad4e1cee0f47f7cbe0b464cc0d549358a190cf71ebe7da7f3eeeb57
[INFO] JSON RPC: getRawTransaction 03aa89d2dad4e1cee0f47f7cbe0b464cc0d549358a190cf71ebe7da7f3eeeb57
SLPJS Validating: 03aa89d2dad4e1cee0f47f7cbe0b464cc0d549358a190cf71ebe7da7f3eeeb57
SLPJS Result: true (03aa89d2dad4e1cee0f47f7cbe0b464cc0d549358a190cf71ebe7da7f3eeeb57)


Docker container:
[INFO] Updating confirmed TNATxn SLP data for 054740694da335b8f80e76dd04dda89a3854b0562f89d9f45e5e0e1b429d79a5
[INFO] JSON RPC: getRawTransaction 054740694da335b8f80e76dd04dda89a3854b0562f89d9f45e5e0e1b429d79a5
SLPJS Validating: 054740694da335b8f80e76dd04dda89a3854b0562f89d9f45e5e0e1b429d79a5
SLPJS Result: true (054740694da335b8f80e76dd04dda89a3854b0562f89d9f45e5e0e1b429d79a5)
[INFO] Updating confirmed TNATxn SLP data for 0524ad004c0064e0254e784ef0cbf9f560d63732d691a3a887715fe0dc215593
[INFO] JSON RPC: getRawTransaction 0524ad004c0064e0254e784ef0cbf9f560d63732d691a3a887715fe0dc215593
SLPJS Validating: 0524ad004c0064e0254e784ef0cbf9f560d63732d691a3a887715fe0dc215593
SLPJS Result: true (0524ad004c0064e0254e784ef0cbf9f560d63732d691a3a887715fe0dc215593)

```

**Comment by christroutner** [comment] 2019-08-30 18:17
I've narrowed the source of the hang-ups to the `updateTxnCollections()` function, specifically internal to the `asyncForEach()` function:
https://github.com/simpleledger/SLPDB/blob/master/SlpGraphManager.ts#L61

At some point the execution is getting stuck inside that `asyncForEach()` function, and it never exits because the promise never resolves. I'm still digging through the code for additional information.

**Comment by christroutner** [comment] 2019-09-01 01:52
I followed the execution path further. I created a fork for SLPDB that I've been running to try and debug exactly where the hang up is occurring.

The furthest I've been able to trace it is this line in index.ts:
https://github.com/simpleledger/SLPDB/blob/master/index.ts#L71

Here is an example of my debugging output right up to where SLPDB hangs:
```
...
SLPJS Validating: a9666af8bbe5ca7af3a6ee86c8333e66b4f578f45b1447660597156e9d61841b
SLPJS Result: true (a9666af8bbe5ca7af3a6ee86c8333e66b4f578f45b1447660597156e9d61841b)
ping 15
ping 21
ping 22
ping 25
ping 26
ping 2
collection: unconfirmed
txid: a9666af8bbe5ca7af3a6ee86c8333e66b4f578f45b1447660597156e9d61841b
tna: null
ping 24
ping 26
ping 27
count: 1
ping 31
Mark 6, updateTxnCollections END
ping 40
ping 41
ping 42
```

The output above starts in the `updateTxnCollections()` function:
https://github.com/christroutner/SLPDB/blob/7f522351ddb0a659ee1e2807a08cbef7541ec97a/SlpGraphManager.ts#L479

It then returns to the `handleConfirmedTxnsMissingSlpMetadata()` function
https://github.com/christroutner/SLPDB/blob/7f522351ddb0a659ee1e2807a08cbef7541ec97a/bit.ts#L334

If finally ends at the `daemon.run` function:
https://github.com/christroutner/SLPDB/blob/7f522351ddb0a659ee1e2807a08cbef7541ec97a/index.ts#L97

I don't see how the `daemon.run` function loops. I see where it gets called at the start, but what is supposed to keep the process running when it gets to the end of the `daemon.run` function?

**Comment by christroutner** [comment] 2019-09-01 15:49
I'll wait for James to confirm this, but it appears that after startup, SLPDB is dependent on the websockets connection to the full node to continue running. If there is any issue with the connection, SLPDB will effectively stall.

**Comment by christroutner** [comment] 2019-09-03 16:15
I've been running SLPDB against an ABC v0.20.0 full node. The hang-up issue in SLPDB always corresponds to seeing this error in the `debug.log` file of my full node:

`socket recv error Connection reset by peer (104)`

It appears that the websocket/ZMQ connection breaks for unknown reasons, and SLPDB never recovers.

**Comment by christroutner** [comment] 2019-09-03 22:15
I forked SLPDB and added these lines to `index.ts`:
https://github.com/christroutner/SLPDB/blob/unstable/index.ts#L74-L79

This sets up a timer that reconnects the websockets/ZMQ every 20 minutes. I've seen a couple of these messages go by:
`socket recv error Connection reset by peer (104)`

...but have not yet seen SLPDB hang up. I'll continue monitoring SLPDB for a couple days to see if this fixes the hang up issue.

**Comment by jcramer** [comment] 2019-09-16 17:30
closing, as we found this was being caused by bad IP address for zmq pubs.  You can now disable SLPDB zmq pubs by setting environment variable: `zmq_outgoing_enable=0`

**Closed by jcramer** 2019-09-16 17:30 UTC
